# © r2 software. All rights reserved.
# MIICA Mobile (Cuadrillas) - Lints configuration

include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint

linter:
  rules:
    always_declare_return_types: true
    prefer_final_locals: true
    require_trailing_commas: true
    use_super_parameters: true
    unawaited_futures: true
    avoid_print: true
    prefer_single_quotes: true
