name: miica_mobile
description: Aplicación móvil de cuadrillas MIICA.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter_riverpod: ^3.0.3
  flutter_secure_storage: ^9.2.4
  go_router: ^16.3.0
  state_notifier: ^0.7.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  custom_lint: ^0.6.4
  # opcional extra de estilo:
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
